FROM ubuntu:latest AS build

RUN apt-get update && apt-get install -y clang-6.0 llvm-6.0 cmake ninja-build python3

COPY . /imlabdb
RUN mkdir -p /imlabdb/docker-build

WORKDIR /imlabdb/docker-build
RUN cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
RUN ninja

FROM scratch
COPY --from=build /imlabdb/docker-build/imlabdb /bin/imlabdb
ENTRYPOINT ["/bin/imlabdb"]
