// ---------------------------------------------------------------------------------------------------
// IMLAB
// ---------------------------------------------------------------------------------------------------
#include "imlab/queryc/query_compiler.h"
#include "imlab/queryc/query_parse_context.h"
#include <sstream>
// ---------------------------------------------------------------------------------------------------
using QueryCompiler = imlab::queryc::QueryCompiler;
// ---------------------------------------------------------------------------------------------------

void QueryCompiler::Compile(Query &query) {
    header_ << R"HEADER(
// ---------------------------------------------------------------------------
// This file is auto-generated.
// Do not edit this file directly.
// ---------------------------------------------------------------------------

#ifndef INCLUDE_IMLAB_COMPILED_QUERY_H_
#define INCLUDE_IMLAB_COMPILED_QUERY_H_

namespace imlab {

    void Run(imlab::Database& db);

}  // namespace imlab
#endif  // INCLUDE_IMLAB_COMPILED_QUERY_H_
)HEADER";

    impl_ << R"IMPL(
// ---------------------------------------------------------------------------
// This file is auto-generated.
// Do not edit this file directly.
// ---------------------------------------------------------------------------

//#include "../../../tools/protobuf/gen/schema.h"
#include "../../../include/database.h"
#include "../../../include/imlab/infra/hash.h"
#include "../../../include/imlab/infra/hash_table.h"
//#include "../../../include/imlab/schemac/schema_parse_context.h"
#include "tbb/tbb.h"
#include <iostream>
#include <iomanip>
#include <mutex>
#include <google/protobuf/descriptor.h>

namespace imlab {

    extern "C" void Run(imlab::Database& db) {
)IMPL";
    query.GenerateCode(impl_);
    impl_ << R"IMPL(
    }

}  // namespace imlab
)IMPL";
}
// ---------------------------------------------------------------------------------------------------
